import type {NextPage} from 'next';
import Head from 'next/head';
import Image from 'next/image';
import {useEffect} from 'react';
import {useQuery} from 'urql';
import {Feed} from '../graphql/__generated__/types';
import {FeedQuery} from '../queries/feeds';
import styles from '../styles/Home.module.css';

type FeedResponse = {
  feeds: Feed[];
};

const Home: NextPage = () => {
  const [result] = useQuery<FeedResponse>({query: FeedQuery});
  console.log('result', result);

  return (
    <div className={styles.container}>
      <Head>
        <title>Simple RSS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Simple RSS</h1>

        {result.data?.feeds?.map(feed => (
          <p key={feed.title}>{feed.rssUrl}</p>
        ))}
      </main>
    </div>
  );
};

export default Home;
